// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Carousel from "./islands/Carousel.tsx";
import * as $CopyButton from "./islands/CopyButton.tsx";
import * as $FloatingButtonIsland from "./islands/FloatingButtonIsland.tsx";
import * as $FormContact from "./islands/FormContact.tsx";
import * as $MenuIcon from "./islands/MenuIcon.tsx";
import * as $OurHistoryIsland from "./islands/OurHistoryIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Carousel.tsx": $Carousel,
    "./islands/CopyButton.tsx": $CopyButton,
    "./islands/FloatingButtonIsland.tsx": $FloatingButtonIsland,
    "./islands/FormContact.tsx": $FormContact,
    "./islands/MenuIcon.tsx": $MenuIcon,
    "./islands/OurHistoryIsland.tsx": $OurHistoryIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
