// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/sendEmail.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/mailerSendConfig.ts";
import * as $$$$$$0 from "./sections/Advantages.tsx";
import * as $$$$$$1 from "./sections/Consultancy.tsx";
import * as $$$$$$2 from "./sections/Contact.tsx";
import * as $$$$$$3 from "./sections/CoreValues.tsx";
import * as $$$$$$4 from "./sections/FloatingButton.tsx";
import * as $$$$$$5 from "./sections/Footer.tsx";
import * as $$$$$$6 from "./sections/Header.tsx";
import * as $$$$$$7 from "./sections/OurHistory.tsx";
import * as $$$$$$8 from "./sections/Partnerships.tsx";
import * as $$$$$$9 from "./sections/Services.tsx";
import * as $$$$$$10 from "./sections/Technologies.tsx";
import * as $$$$$$11 from "./sections/Theme/Theme.tsx";
import * as $$$$$$12 from "./sections/WhatSayAboutUs.tsx";

const manifest = {
  "loaders": {
    "site/loaders/mailerSendConfig.ts": $$$0,
  },
  "sections": {
    "site/sections/Advantages.tsx": $$$$$$0,
    "site/sections/Consultancy.tsx": $$$$$$1,
    "site/sections/Contact.tsx": $$$$$$2,
    "site/sections/CoreValues.tsx": $$$$$$3,
    "site/sections/FloatingButton.tsx": $$$$$$4,
    "site/sections/Footer.tsx": $$$$$$5,
    "site/sections/Header.tsx": $$$$$$6,
    "site/sections/OurHistory.tsx": $$$$$$7,
    "site/sections/Partnerships.tsx": $$$$$$8,
    "site/sections/Services.tsx": $$$$$$9,
    "site/sections/Technologies.tsx": $$$$$$10,
    "site/sections/Theme/Theme.tsx": $$$$$$11,
    "site/sections/WhatSayAboutUs.tsx": $$$$$$12,
  },
  "actions": {
    "site/actions/sendEmail.ts": $$$$$$$$$0,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
